---
- name: Copy file with owner and permissions
  hosts: MAC
  connection: local
  tasks:
    - name: Coping folder
      copy:
        src: /Users/*/ansible/file_copy/
        dest: /tmp

    - name: checking space
      setup:
       gather_subset:
       - 'hardware'
