---
- name: Copy file with owner and permissions
  hosts: MAC
  connection: local
  vars_files:
    - variables.yml
  tasks:
    - name: Coping folder
      copy:
        src: "{{src}}"
        dest: "{{dest}}"

    - name: checking space
      setup:
       gather_subset:
       - 'hardware'
